media:
  input: src/assets/images
  output: /media

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: 'src/content/blog'
    view:
      fields: [title, date, image, tags]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Publication Date
        type: date
      - name: excerpt
        label: Excerpt
        type: string
      - name: lastModified
        label: Last Modified
        type: date
        required: false
      - name: image
        label: Featured Image
        type: image
      - name: coverAlt
        label: Image Alt Text
        type: string
        required: false
      - name: category
        label: Categories
        type: list
        required: false
      - name: tags
        label: Tags
        type: list
      - name: author
        label: Author
        type: string
        required: false
      - name: body
        label: Content
        type: rich-text
      - name: metadata
        label: Metadata
        type: object
        required: false
        fields:
          - name: title
            label: Meta Title
            type: string
            required: false
          - name: image
            label: Meta Image
            type: image
            required: false
          - name: ignoreTitleTemplate
            label: Ignore Title Template
            type: boolean
            required: false
          - name: canonical
            label: Canonical URL
            type: string
            required: false
            pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
          - name: description
            label: Meta Description
            type: string
            required: false
          - name: robots
            label: Robots
            type: object
            required: false
            fields:
              - name: index
                label: Index
                type: boolean
                required: false
              - name: follow
                label: Follow
                type: boolean
                required: false
          - name: openGraph
            label: Open Graph
            type: object
            required: false
            fields:
              - name: url
                label: URL
                type: string
                required: false
                pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
              - name: siteName
                label: Site Name
                type: string
                required: false
              - name: locale
                label: Locale
                type: string
                required: false
              - name: type
                label: Type
                type: string
                required: false
              - name: images
                label: Images
                type: list
                required: false
                fields:
                  - name: url
                    label: URL
                    type: string
                    required: true
                  - name: width
                    label: Width
                    type: number
                    required: false
                  - name: height
                    label: Height
                    type: number
                    required: false
          - name: twitter
            label: Twitter
            type: object
            required: false
            fields:
              - name: handle
                label: Handle
                type: string
                required: false
              - name: site
                label: Site
                type: string
                required: false
              - name: cardType
                label: Card Type
                type: string
                required: false

  - name: update
    label: Updates
    type: collection
    path: 'src/content/update'
    view:
      fields: [title, date, image]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Publication Date
        type: date
      - name: excerpt
        label: Excerpt
        type: string
      - name: lastModified
        label: Last Modified
        type: date
        required: false
      - name: image
        label: Featured Image
        type: image
      - name: coverAlt
        label: Image Alt Text
        type: string
        required: false
      - name: category
        label: Categories
        type: list
        required: false
      - name: tags
        label: Tags
        type: list
        required: false
      - name: author
        label: Author
        type: string
        required: false
      - name: body
        label: Content
        type: rich-text
      - name: metadata
        label: Metadata
        type: object
        required: false
        fields:
          - name: title
            label: Meta Title
            type: string
            required: false
          - name: image
            label: Meta Image
            type: image
            required: false
          - name: ignoreTitleTemplate
            label: Ignore Title Template
            type: boolean
            required: false
          - name: canonical
            label: Canonical URL
            type: string
            required: false
            pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
          - name: description
            label: Meta Description
            type: string
            required: false
          - name: robots
            label: Robots
            type: object
            required: false
            fields:
              - name: index
                label: Index
                type: boolean
                required: false
              - name: follow
                label: Follow
                type: boolean
                required: false
          - name: openGraph
            label: Open Graph
            type: object
            required: false
            fields:
              - name: url
                label: URL
                type: string
                required: false
                pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
              - name: siteName
                label: Site Name
                type: string
                required: false
              - name: locale
                label: Locale
                type: string
                required: false
              - name: type
                label: Type
                type: string
                required: false
              - name: images
                label: Images
                type: list
                required: false
                fields:
                  - name: url
                    label: URL
                    type: string
                    required: true
                  - name: width
                    label: Width
                    type: number
                    required: false
                  - name: height
                    label: Height
                    type: number
                    required: false
          - name: twitter
            label: Twitter
            type: object
            required: false
            fields:
              - name: handle
                label: Handle
                type: string
                required: false
              - name: site
                label: Site
                type: string
                required: false
              - name: cardType
                label: Card Type
                type: string
                required: false

  - name: marketing
    label: Marketing Pages
    type: collection
    path: 'src/content/marketing'
    view:
      fields: [title, date, updateDate]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Publication Date
        type: date
        required: false
      - name: updateDate
        label: Update Date
        type: date
        required: false
      - name: excerpt
        label: Excerpt
        type: string
        required: false
      - name: image
        label: Featured Image
        type: image
        required: false
      - name: body
        label: Content
        type: rich-text
      - name: metadata
        label: Metadata
        type: object
        required: false
        fields:
          - name: title
            label: Meta Title
            type: string
            required: false
          - name: image
            label: Meta Image
            type: image
            required: false
          - name: ignoreTitleTemplate
            label: Ignore Title Template
            type: boolean
            required: false
          - name: canonical
            label: Canonical URL
            type: string
            required: false
            pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
          - name: description
            label: Meta Description
            type: string
            required: false
          - name: robots
            label: Robots
            type: object
            required: false
            fields:
              - name: index
                label: Index
                type: boolean
                required: false
              - name: follow
                label: Follow
                type: boolean
                required: false
          - name: openGraph
            label: Open Graph
            type: object
            required: false
            fields:
              - name: url
                label: URL
                type: string
                required: false
                pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
              - name: siteName
                label: Site Name
                type: string
                required: false
              - name: locale
                label: Locale
                type: string
                required: false
              - name: type
                label: Type
                type: string
                required: false
              - name: images
                label: Images
                type: list
                required: false
                fields:
                  - name: url
                    label: URL
                    type: string
                    required: true
                  - name: width
                    label: Width
                    type: number
                    required: false
                  - name: height
                    label: Height
                    type: number
                    required: false
          - name: twitter
            label: Twitter
            type: object
            required: false
            fields:
              - name: handle
                label: Handle
                type: string
                required: false
              - name: site
                label: Site
                type: string
                required: false
              - name: cardType
                label: Card Type
                type: string
                required: false

  - name: docs
    label: Documentation
    type: collection
    path: 'src/content/docs'
    view:
      fields: [title, description]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
        required: false
      - name: sidebar
        label: Sidebar Configuration
        type: object
        required: false
        fields:
          - name: label
            label: Sidebar Label
            type: string
            required: false
          - name: order
            label: Order
            type: number
            required: false
      - name: hero
        label: Hero Section
        type: object
        required: false
        fields:
          - name: title
            label: Hero Title
            type: string
            required: false
          - name: tagline
            label: Hero Tagline
            type: string
            required: false
          - name: image
            label: Hero Image
            type: image
            required: false
      - name: lastUpdated
        label: Last Updated Date
        type: date
        required: false
      - name: body
        label: Content
        type: rich-text

  - name: site
    label: Site Settings
    type: file
    path: 'src/_data/site.json'
    fields:
      - name: title
        label: Website Title
        type: string
      - name: description
        label: Website Description
        type: string
        description: Will be used for any page with no description
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview Image
        type: image
        description: Image used in social previews on social networks